FROM python:3.10
WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY feat_eng_pipeline.py /app/

COPY listener.py /app/

CMD ["python", "/app/listener.py"]